### ISSUE TITLE
Q: what do you use for orchestration?

### ISSUE THREAD

**Issue by guang** [gettyimages/docker-spark#5]
Hi there!

Thanks for the awesome work, got this to work locally via docker compose in no time - I was just curious what tools do you guys to orchestrate spark containers in a cluster?

While compose translates well to using docker swarm, kubernetes's core concepts (pods, services, and replication controllers) make a lot more sense to me. It would be awesome if you guys could share a little bit about how you orchestrate spark containers in a cluster :D

**Comment by dylanmei** [comment]
Hello,

In the past we used the [CoreOS/Fleet](https://coreos.com/using-coreos/clustering) pattern to create Spark [standalone clusters](http://spark.apache.org/docs/latest/spark-standalone.html) with the `gettyimages/spark` as a base docker-image. On top of the base image we added [ConfD](http://www.confd.io), [Prometheus](http://prometheus.io) [jmx_exporter](https://github.com/prometheus/jmx_exporter), and other bits and pieces of customization.

But Fleet is a clumsy scheduler, and using a single stand-alone cluster manager becomes difficult because it limits your developers to a certain version of Spark.

These days we use Spark's [Mesos](http://spark.apache.org/docs/latest/running-on-mesos.html) framework in production, and use the `gettyimages/spark` image for local development using docker-compose.

Kubernetes is also an attractive scheduler.
