### ISSUE TITLE
Multiple worker setup

### ISSUE THREAD

**Issue by l15k4** [gettyimages/docker-spark#7]
Hey,

I'm trying to leverage `m4.4xlarge` machine in a single-node setup so I'd like to run 2 workers. I guess that setting `SPARK_WORKER_INSTANCES: 2` still creates just a single worker, right? Do I have to create 2 `worker` containers, each with `SPARK_WORKER_INSTANCES: 2` ?

This `SPARK_WORKER_INSTANCES` is somewhat misleading because imho one has to create an extra `org.apache.spark.deploy.worker.Worker` process/container explicitly.

**Comment by dylanmei** [comment]
For two workers on same host, instead of

```
worker:
  image: gettyimages/spark
  #...
```

You'd want

```
worker1:
  image: gettyimages/spark
  #...

worker2:
  image: gettyimages/spark
  #...
```

You would also need separate `conf/worker/spark-defaults.conf` settings and expose different ports to deal with conflicts on your host.

[Newer versions of docker-compose (1.6.0+) allow you to do more creative things with networks](https://docs.docker.com/compose/networking/) to make this easier, but I don't have much experience with that.

But ultimately, you'd just be distributing workers across the same host's resources, so you really won't get any benefit, and will probably run worse, than just using `docker run` and `/usr/spark/bin/spark-submit` or `/usr/spark/bin/spark-shell` directly in `local` mode.

Example reading from S3:

```
docker run --rm -it -e "AWS_ACCESS_KEY_ID=YOURKEY" -e "AWS_SECRET_ACCESS_KEY=YOURSECRET" -e "$AWS_DEFAULT_REGION=us-west-2" gettyimages/spark bin/spark-shell
> val docs = sqlContext.read.json("s3n://my-bucket/docs.json")
> docs.registerTempTable("docs")
```

**Comment by l15k4** [comment]
Perfect, I just thought that 64GB machines should run multiple workers (jvm processes) because of GC issues. So starting 2 workers with `SPARK_WORKER_INSTANCES: 2` is probably the way. 

I switched from multi-node CoreOS setup to a single node docker-compose setup on one strong machine after a year in production (tons of issues)....

I suspect that this project cannot be used on a multi-node cluster because it lacks service discovery, right? The biggest docker-compose drawback ...

I'm starting to wonder why people use multi-node cluster setup when they can use `m4.10xlarge` spot instances with multiple workers

**Comment by dylanmei** [comment]
We have used the container in a Spark-standalone cluster and a Mesos cluster. The docker-compose file in this repo is for developers who might want to make sure they are running correctly in a distributed environment, doing broadcast variables correctly, writing metrics/logs correctly, etc. It's not for serious use.

**Comment by cgarciae** [comment]
@l15k4 You could also use `docker-compose scale worker=2` or any arbitrary number. Just set all ports from the worker to be chosen randomly to avoid conflicts.

**Comment by yeikel** [comment]
@cgarciae Can you please explain this step `Just set all ports from the worker to be chosen randomly to avoid conflicts.` 

Thank you

**Comment by cgarciae** [comment]
@yeikel Normally you specify the port on the host like this:

```
ports:
  - "3000:3000"
```
but if you just specify a single port like this:
```
ports:
  - "3000"
```
the port on the host is chosen to a random port available.

**Comment by yeikel** [comment]
@cgarciae Thank you
